name: create preview renders

on:
  push:
    branches: [ * ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install requirements
      run: aptitude install asciidoctor asciidoctor-pdf
    
    - name: render preview
      run: make preview
